<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/jumbotron-narrow/">

    <title>Narrow Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Início</a></li>
            <li role="presentation"><a href="/cadastrar/index">Cadastrar</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Avaliação Técnica PHP</h3><hr>
      </div>

      <div class="row marketing">
        <div class="col-lg-8">
            <div class="row text-center">
                <h4>Pessoas Cadastradas</h4>
            </div>
        
          <table class=" table table-striped">
            <tr>
                <th>Nome</th>
                <th>Foto</th>
                <th>E-mail</th>
                <th>Data Nascimento</th>
                <th>Localidade</th>
                <th>Interesse</th>
                <th>Visualizar</th>
            </tr>                        
            <?php
               if(sizeof($this->paginator)):?>  
               <?php foreach($this->paginator as $pessoa):?>
                  
           
                    <tr>
                        <td><?php echo $pessoa["name"];?></td>
                        <td><img src="<?php echo $pessoa["foto"];?>"></td>
                        <td><?php echo $pessoa["email"];?></td>
                        <td><?php echo $pessoa["dt_nasc"];?></td>
                        <td><?php echo $pessoa["localidade"];?></td>
                        <td><?php echo $pessoa["interesse"];?></td>
                        <td>
                            <a href="<?php echo $this->url(array('controller' => 'visualizar', 'action' => 'index', 'id'=> $pessoa["id"])); ?>">
                                <i class="glyphicon glyphicon-search"></i>
                            </a>
                       </td>
                    </tr>
            <?php
                    endforeach;
                else:                
            ?>
            <div>Nenhuma pessoa cadastrada</div>
            <?php endif; ?>
          <?php echo $this->paginator;?> 
          </table>
        </div>
        
      </div>
 

     

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
