 <nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar" aria-expanded="false"
			aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
			<span class="icon-bar"></span> <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="../index">Primeiro Projeto</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<li><a href="../index">Início</a></li>
			<li class="active"><a href="sobre">Sobre</a></li>
			<li><a href="../contato/contato" class="active">Contato</a></li>
		</ul>
	</div>
	<!--/.nav-collapse -->
</div>
</nav>
<div style="height:70px;" class="row col-md-12"></div>
<div class="container theme-showcase" role="main">

	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Sobre</h1>
		<p>A Projeto Web foi fundada em 2015 na cidade de Brasília pelo Senhor
			João da Silva e sua principal missão (colocar aqui a missão da
			empresa). Atualmente contamos com 1 funcionário e nossos principais
			clientes são nome dos clientes, separados por vírgula.</p>
	</div>
	<div class="page-header">
		<h1>Galeria de Imagens</h1>
	</div>
	<div id="carousel-example-generic" class="carousel slide"
		data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0"
				class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="../img/img1.png"
					alt="First slide">
			</div>
			<div class="item">
				<img src="../img/img2.png"
					alt="Second slide">
			</div>
			<div class="item">
				<img src="../img/img3.png"
					alt="Third slide">
			</div>
		</div>
		<a class="left carousel-control" href="#carousel-example-generic"
			role="button" data-slide="prev"> <span
			class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
			class="sr-only">Previous</span>
		</a> <a class="right carousel-control"
			href="#carousel-example-generic" role="button" data-slide="next"> <span
			class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<hr>
	<footer class="footer">
		<p>&copy; Company 2015</p>
	</footer>

</div>
<!-- /container -->