<script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>
<link href="css/estilo-narrow.css" rel="stylesheet">
 <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">inicio</a></li>
            <li role="presentation"><a href="#">sobre</a></li>
            <li role="presentation"><a href="#">areas atuacao</a></li>
            <li role="presentation"><a href="#">contato</a></li>
            <li role="presentation"><a href="auth/logout">sair</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Primeiro Projeto</h3>
      </div>
        <div class="col-md-12">
            atuacao
        </div>
          <div class="col-md-12">
              <footer class="footer">
                <p>&copy; Company 2014</p>
              </footer>
          </div>

    </div> <!-- /container -->
