<script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
  tinymce.init({
      selector: "textarea",
      plugins: [
          "advlist autolink lists link image charmap print preview anchor",
          "searchreplace visualblocks code fullscreen",
          "insertdatetime media table contextmenu paste"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
  });
</script>
 

<!DOCTYPE html>
<html lang="en">

<head>    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="../public">Marra Advocacia</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>                               
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="auth/logout"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="arearestrita"><i class="fa fa-home fa-fw"></i> Página Principal</a>
                        </li>
                        <li>
                            <a href="arearestrita/atuacao"><i class="fa fa-bar-chart-o fa-fw"></i> Atuação</a>
                        </li>                        
                        <li>
                            <a href="arearestrita/sobre"><i class="fa fa-table fa-fw"></i> Sobre</a>
                        </li>
                        <li>
                            <a href="arearestrita/contato"><i class="fa fa-edit fa-fw"></i> Contato</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Página Principal</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>           
            <div class="row">
                <div class="col-lg-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Texto Principal                                                      
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <form id="" name="" action="" method="">
                                <input type="hidden" id="principal" name="principal" value="<?php if($this->textoprincipal){foreach ($this->textoprincipal as $textop){echo $textop->id;}}?>"/>
                                <input type="hidden" id="id_principal" name="id_principal" value="1"/>
                                <div style="padding:15px;" class="row">
                                    <div class="row col-lg-12">
                                        <span>Título Principal: </span><input id="titulop" name="titulop" class="form-control" value="<?php if($this->textoprincipal){foreach ($this->textoprincipal as $textop){echo $textop->ini_titulo;}}?>"/>
                                    </div>  
                                    <div class="row col-lg-12">  
                                        <span>Texto: </span>
                                        <textarea name="contentp" style="width:100%"><?php if($this->textoprincipal){foreach ($this->textoprincipal as $textop){ echo utf8_decode($textop->ini_descricao);}}?></textarea>
                                    </div>
                                    <div class="row col-lg-12 text-right">
                                        <input class="btn btn-success" type="submit" value="Salvar"/>
                                    </div>  
                                </div>
                            </form>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Notícias
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                             <form id="" name="" action="" method="">
                                <div style="padding:15px;" class="row">
                                    <input type="hidden" id="id_noticia" name="id_noticia" value="1"/>
                                    <div class="row col-lg-4">
                                        <span>Título: </span><input id="titulo" name="titulo" class="form-control" />
                                    </div>
                                    <div class="row col-lg-4">
                                        <span>Data: </span><input id="data" name="data" class="form-control" value=""/>
                                    </div> 
                                    <div class="row col-lg-4">
                                        <span>Autor: </span><input id="autor" name="autor" class="form-control" />
                                    </div>  
                                    <div class="row col-lg-12">  
                                        <span>Texto: </span>
                                        <textarea name="content" style="width:100%"></textarea>
                                    </div>
                                    <div class="row col-lg-12 text-right">
                                        <input class="btn btn-success" type="submit" value="Salvar"/>
                                    </div>  
                                </div>
                                <!-- /.row -->
                             </form>   
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> Galeria de Imagens
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div style="padding:15px;">
                                <div class="col-lg-8">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <img src="img/img1.png" alt="..." class="img-rounded img-responsive">
                                        </div>
                                        <div style="padding-top:20px;" class="col-lg-6">
                                            <i class="glyphicon glyphicon-remove text-danger"></i>
                                        </div>
                                    </div>  
                                    <div class="row">  
                                        <div class="col-lg-6">
                                            <img src="img/img2.png" alt="..." class="img-rounded img-responsive">
                                        </div> 
                                        <div style="padding-top:20px;" class="col-lg-6">
                                           <i class="glyphicon glyphicon-remove text-danger"></i>
                                        </div>
                                    </div>
                                    <div class="row">    
                                        <div class="col-lg-6">
                                            <img src="img/img3.png" alt="..." class="img-rounded img-responsive">
                                        </div>   
                                        <div style="padding-top:20px;" class="col-lg-6">
                                            <i class="glyphicon glyphicon-remove text-danger"></i>
                                        </div>
                                    </div> <br />
                                    <div class="row">
                                        <input type="file" name="imagem"/>
                                    </div>                                                            
                                </div>
                                <div class="row col-lg-12 text-right">
                                    <input class="btn btn-success" type="submit" value="Salvar"/>
                                </div> 
                            </div> 
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Redes Sociais
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <span>redes sociais</span>
                            <div class="row col-lg-12 text-right">
                                <input class="btn btn-success" type="submit" value="Salvar"/>
                            </div> 
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->                   
                </div>
                
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    
    <!-- Metis Menu Plugin JavaScript -->
    <script src="bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="bower_components/raphael/raphael-min.js"></script>
    <script src="bower_components/morrisjs/morris.min.js"></script>
    <script src="js/morris-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="dist/js/sb-admin-2.js"></script>

</body>

</html>
