<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/jumbotron-narrow/">

    <title>Narrow Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" ><a href="/index/index">Início</a></li>
            <li role="presentation" ><a href="cadastrar">Cadastrar</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Visualizar Pessoa</h3>
      </div>        
  
      <div class="text-center">
        <?php
            if ($this->pessoa) {
              foreach ($this->pessoa as $pessoa) {
        ?>
        <div class="panel panel-default">
          <div class="panel-body">
              <div class="col-md-12 row">
                <div class=col-md-8>
                  <h3><?php echo $pessoa['name']; ?></h3>
                </div>
                <div class=col-md-4>
                  <img src="<?php echo $pessoa["foto"];?>">
                </div>
              </div>
              <div class="col-md-12">
                  <!-- Table -->
                  <table class="table">
                    <tr>
                        <th>Email</th>
                        <th>Data de Nascimento</th>
                        <th>Localidade</th>
                        <th>Interesse</th>
                    </tr>
                    <tr class="text-left">
                        <td><?php echo $pessoa["email"];?></td>
                        <td><?php echo $pessoa["dt_nasc"];?></td>
                        <td><?php echo $pessoa["localidade"];?></td>
                        <td><?php echo $pessoa["interesse"];?></td>
                    </tr>
                  </table>
              </div>
         
        </div>
            
        
        <?php } }?> 
        
      </div>
      
    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
