<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar" aria-expanded="false"
			aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
			<span class="icon-bar"></span> <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="../index">Primeiro Projeto</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<li><a href="index">Início</a></li>
			<li class=""><a href="sobre">Sobre</a></li>
			<li class="active"><a href="atuacao">Áreas de Atuação</a></li>
			<li><a href="contato" class="active">Contato</a></li>
		</ul>
	</div>
	<!--/.nav-collapse -->
</div>
</nav>
<div style="height:70px;" class="row col-md-12"></div>
<div class="container theme-showcase" role="main">

	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Áreas de Atuação</h1>
		<p>A Projeto Web foi fundada em 2015 na cidade de Brasília pelo Senhor
			João da Silva e sua principal missão (colocar aqui a missão da
			empresa). Atualmente contamos com 1 funcionário e nossos principais
			clientes são nome dos clientes, separados por vírgula.</p>
	</div>   
     <!-- Three columns of text below the carousel -->
      <div class="row text-center">
        <div class="col-lg-4">
          <img class="img-circle" src="img/img_direito_trabalho.jpg" alt="Imagem direito trabalho" style="width: 140px; height: 140px;">
          <h2>Direito do Trabalho</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="img/img_direito_previdenciaro.png" alt="Imagem direito previdenciario" style="width: 140px; height: 140px;">
          <h2>Direito Previdenciário</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="img/img_direito_civil.jpg" alt="Imagem direito civil" style="width: 140px; height: 140px;">
          <h2>Direito Civil</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>         
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
      <hr />
	<footer class="footer">
        <strong><p class="pull-right"><a href="#">Voltar ao topo</a></p></strong>
		<p>&copy; Company 2015</p>
	</footer>

</div>
<!-- /container -->