<?php echo $this->Doctype()?>

<html>
	<head>
  	<meta content=&quot;IE=9&quot; http-equiv=&quot;X-UA-Compatible&quot; />
    <title>Primeiro Projeto</title>
     	<?php echo $this->headTitle()?>	
		<?php echo $this->headLink()?>
		<?php echo $this->headScript()?>			
	</head>	
	<body id="">               
        <div id="content">        	
        	<?php echo $this->layout()->content?>        	
        </div>      
        		                    
	</body>
</html>