<link href="css/login.css" media="screen" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="col-md-12">
        <div class="col-md-4">
        
        </div>
        <div class="col-md-4">
          <form class="form-signin" action="" method="post">
            <h2 class="form-signin-heading">Login</h2>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="text" id="login" name="login" class="form-control" placeholder="Usuário" required autofocus>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" id="senha" name="senha" class="form-control" placeholder="Senha" required>
            <div class="checkbox">
              <label>
                <a href="#"> Esqueceu sua senha?</a>
              </label>
              <label>
                <a href="index">Voltar para o site</a>
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
          </form>
        </div>
        <div class="col-md-4">
        
        </div>
    </div>
    </div> <!-- /container -->