<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar" aria-expanded="false"
			aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
			<span class="icon-bar"></span> <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="../index">Primeiro Projeto</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<li><a href="../index">Início</a></li>
			<li><a href="../sobre/sobre">Sobre</a></li>
			<li class="active"><a href="contato" class="active">Contato</a></li>
		</ul>
	</div>
	<!--/.nav-collapse -->
</div>
</nav>
<div style="height:70px;" class="row col-md-12"></div>
<div class="container theme-showcase" role="main">

	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Contato</h1>
		<p>This is a template showcasing the optional theme stylesheet
			included in Bootstrap. Use it as a starting point to create something
			more unique by building on or modifying it.</p>
	</div>
	<div class="row container">
        <div style="margin-top:25px;" class="col-md-6 well">
            <span>
                Fique à vontade para nos contatar a qualquer momento através do formulário abaixo. Estamos ansiosos para ouvi-lo(a). 
                Caso tenha interesse em fazer parte de nossa equipe, por favor envie seu currículo para o endereço selecao@camposmello.adv.br, indicando sua área de interesse.
            </span>
        </div>
        <div class="col-md-6">            
    		<form>
    			<div class="form-group">
    				<label for="exampleInputEmail1">Email</label> <input type="email"
    					class="form-control" id="exampleInputEmail1"
    					placeholder="Enter email">
    			</div>
    			<div class="form-group">
    				<label for="exampleInputPassword1">Texto</label>
    				<textarea class="form-control" rows="5"></textarea>
    			</div>
    			<button type="submit" class="btn btn-primary">Enviar</button>
    		</form>
        </div>        
	</div>
	<div class="page-header">
		<h1>Galeria de Imagens</h1>
	</div>
	<div id="carousel-example-generic" class="carousel slide"
		data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0"
				class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="../img/img1.png"
					alt="First slide">
			</div>
			<div class="item">
				<img src="../img/img2.png"
					alt="Second slide">
			</div>
			<div class="item">
				<img src="../img/img3.png"
					alt="Third slide">
			</div>
		</div>
		<a class="left carousel-control" href="#carousel-example-generic"
			role="button" data-slide="prev"> <span
			class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
			class="sr-only">Previous</span>
		</a> <a class="right carousel-control"
			href="#carousel-example-generic" role="button" data-slide="next"> <span
			class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<hr>
	<footer class="footer">
		<p>&copy; Company 2015</p>
	</footer>

</div>
<!-- /container -->
