<script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=ABQIAAAA6cQIrMEc9zlaKBjWiPM5rxSjlBXfTSDcGsB79vzL90uiOHMpbBRa1FFoX2YfuQNFvFKxQtpz0ZCeuw&amp;hl=en"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
<head>
<script type="text/javascript" src="js/jquery.gmap-1.1.0-min.js"></script>
<script type="text/javascript" src="js/jquery.scrollTo-1.4.2-min.js"></script>
<script type="text/javascript" src="js/jquery.localscroll-1.2.7-min.js"></script>
<script type='text/javascript' charset='utf-8'>
 
$(document).ready(function(){		
		$("#map").gMap({ markers: [{ latitude: -15.895771, 
                              longitude: -47.776103,
                              html: "Marra Advocacia",                              
                              popup: true }],
                  zoom: 15
              });		    	 	      
	});   

	
</script>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar" aria-expanded="false"
			aria-controls="navbar">
			<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
			<span class="icon-bar"></span> <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="index">Marra Advocacia</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
		<ul class="nav navbar-nav">
			<li><a href="index">Início</a></li>
			<li><a href="sobre">Sobre Nós</a></li>
            <li class=""><a href="atuacao">Áreas de Atuação</a></li>
            <li><a href="noticias">Publicações</a></li>
			<li class="active"><a href="contato" class="active">Contato</a></li>
		</ul>
        <div style="padding:15px;" class="text-right">
                    <a id="" href="auth"><i class="glyphicon glyphicon-lock"></i></a>         
                </div>
	</div>
	<!--/.nav-collapse -->
</div>
</nav>
<div style="height:70px;" class="row col-md-12"></div>
<div class="container theme-showcase" role="main">
	<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Contato</h1>
		<p>This is a template showcasing the optional theme stylesheet
			included in Bootstrap. Use it as a starting point to create something
			more unique by building on or modifying it.</p>
	</div>
	<div class="row container">
        <div class="col-md-5">
            <div style="margin-top:0px;" class="col-md-12 well">
                <span>
                    Fique à vontade para nos contatar a qualquer momento através do formulário a seguir. Estamos ansiosos para ouvi-lo(a).                
                </span>
                <address>
                <strong>Twitter, Inc.</strong><br>
                  795 Folsom Ave, Suite 600<br>
                  San Francisco, CA 94107<br>
                  <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>            
                <address>
                  <strong>Full Name</strong><br>
                  <a href="mailto:#">first.last@example.com</a>
                </address>
            </div>
            <div class="col-md-12">            
        		<form>
        			<div class="form-group">
        				<label for="exampleInputText1">Nome</label> <input type="text"
        					class="form-control" id="exampleInputText"
        					placeholder="Enter nome">
        			</div>
        			<div class="form-group">
        				<label for="exampleInputEmail1">Email</label> <input type="email"
        					class="form-control" id="exampleInputEmail1"
        					placeholder="Enter email">
        			</div>
        			<div class="form-group">
        				<label for="exampleInputPassword1">Texto</label>
        				<textarea class="form-control" rows="3"></textarea>
        			</div>
        			<button type="submit" class="btn btn-primary">Enviar</button>
        		</form>
            </div>
        </div>  
		<div class="col-md-7">
        	<div id="map" style="min-width:200px; height:400px ; border: 1px solid #ccc; overflow: hidden;"></div>
        </div>
	</div>
	<hr>
	<footer class="footer">
        <strong><p class="pull-right"><a href="#">Voltar ao topo</a></p></strong>
		<p>&copy; Company 2015</p>
	</footer>

</div>
<!-- /container -->
