<head>    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content=""><!-- CSS -->
    <link href="css/noticias.css" rel="stylesheet">
</head>
<body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="./index"><i class="glyphicon glyphicon-home"></i> Marra Advocacia</a>
        </nav>
      </div>
    </div>

    <div class="container">
        
      <div class="blog-header">
        <h1 class="blog-title">Marra Advocacia Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <h2 class="blog-post-title"><?php if($this->noticias){foreach($this->noticias as $noticias){echo utf8_decode($noticias->titulo_noticia);}}?></h2>
            <p class="blog-post-meta">January 1, 2014 by <a href="#"><?php if($this->noticias){foreach($this->noticias as $noticias){echo utf8_decode($noticias->autor_noticia);}}?></a></p>
            <p><?php if($this->noticias){foreach($this->noticias as $noticias){echo utf8_decode($noticias->corpo_noticia);}}?></p>
            
          </div><!-- /.blog-post -->
          <nav>
            <ul class="pager">
              <li><a href="#">Anterior</a></li>
              <li><a href="#"><?php echo utf8_decode("Próximo");?></a></li>
            </ul>
          </nav>
        </div><!-- /.blog-main -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>